### ISSUE TITLE
Error logs during tests

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1161]
Current test output contains several error logs

```
PASS packages/jbrowse-web/src/tests/JBrowse.test.js (11.679s)
  ● Console
    console.error node_modules/react-dom/cjs/react-dom.development.js:88
      Warning: Expected server HTML to contain a matching <rect> in <svg>.
          in rect (at SvgOverlay.tsx:92)
          in OverlayRect (at SvgOverlay.tsx:219)
          in SvgOverlay (at SvgFeatureRendering.js:341)
          in svg (at SvgFeatureRendering.js:316)
          in div (at SvgFeatureRendering.js:315)
          in SvgFeatureRendering
          in SvgFeatureRendering
PASS packages/data-management/src/AddTrackWidget/components/AddTrackWidget.test.js
PASS packages/alignments/src/index.test.ts
  ● Console
    console.error node_modules/mobx/lib/mobx.js:1815
      [mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Autorun@207]' Error: no containing view found
          at getContainingView (/home/travis/build/GMOD/jbrowse-components/packages/core/util/index.ts:245:11)
          at /home/travis/build/GMOD/jbrowse-components/packages/linear-genome-view/src/BasicTrack/blockBasedTrackModel.ts:189:22
          at reactionRunner (/home/travis/build/GMOD/jbrowse-components/node_modules/mobx/lib/mobx.js:2086:9)
          at trackDerivedFunction (/home/travis/build/GMOD/jbrowse-components/node_modules/mobx/lib/mobx.js:757:24)
          at Reaction.Object.<anonymous>.Reaction.track (/home/travis/build/GMOD/jbrowse-components/node_modules/mobx/lib/mobx.js:1786:22)
          at Reaction.onInvalidate (/home/travis/build/GMOD/jbrowse-components/node_modules/mobx/lib/mobx.js:2067:18)
          at Reaction.Object.<anonymous>.Reaction.runReaction (/home/travis/build/GMOD/jbrowse-components/node_modules/mobx/lib/mobx.js:1752:26)
          at runReactionsHelper (/home/travis/build/GMOD/jbrowse-components/node_modules/mobx/lib/mobx.js:1889:35)
          at reactionScheduler (/home/travis/build/GMOD/jbrowse-components/node_modules/mobx/lib/mobx.js:1867:47)
          at /home/travis/build/GMOD/jbrowse-components/node_modules/mobx/lib/mobx.js:1896:71
          at batchedUpdates$1 (/home/travis/build/GMOD/jbrowse-components/node_modules/react-dom/cjs/react-dom.development.js:21856:12)
          at reactionScheduler (/home/travis/build/GMOD/jbrowse-components/node_modules/mobx/lib/mobx.js:1896:47)
          at runReactions (/home/travis/build/GMOD/jbrowse-components/node_modules/mobx/lib/mobx.js:1872:5)
```

If these are expected we should use mock console to silence them. Note that the

JBrowse.test.js has the rect overlay error:

      Warning: Expected server HTML to contain a matching <rect> in <svg>.

Note that this error can occur in normal dev environment, has been observed for a long time....might technically need fixing to make sure selected feature is passed to the backend? Unless it is an actual race condition?

The other error about no containing view comes from
packages/alignments/src/index.test.ts

The alignments track had attempted to isolate itself way long time ago (similar to https://github.com/GMOD/jbrowse-components/issues/1159) but probably needs an update now

**Comment by cmdcolin** [comment]
Probably going to delete the tests in packages/alignments/src/index.test.ts they are just too weird I think...

**Comment by cmdcolin** [comment]
The Expected server HTML to contain a matching rect remains something that might need consideration. This one is interesting because it might be the result of featureIdUnderMouse? Not really sure yet.

**Comment by cmdcolin** [comment]
Any ideas for this one?

**Comment by cmdcolin** [comment]
It is sort of "not harmful" in a way but it happens at runtime and at test time and could indicate some weirdness with our use of ssr
