### ISSUE TITLE
Auto-deploy builds of jbrowse-desktop

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1214]
Use github actions or travis-CI probably

**Comment by cmdcolin** [comment]
Random thing but I am currently unable to run

yarn build-electron:linux on my computer

```
yarn build-electron:linux
yarn run v1.22.4
$ yarn build && electron-builder build --linux
$ rescripts build
Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  599.25 KB  build/static/js/1.26c870d3.chunk.js
  166.57 KB  build/static/js/main.201774cd.chunk.js
  158.51 KB  build/static/js/rpc.0ddee3ac.chunk.js
  4.49 KB    build/static/js/4.209c8c5d.chunk.js
  785 B      build/static/js/runtime.31763979.js
  679 B      build/static/css/1.e899142f.chunk.css
  587 B      build/static/css/4.ba36a308.chunk.css
  473 B      build/static/css/main.8e0bc2d6.chunk.css
  473 B      build/static/css/rpc.8e0bc2d6.chunk.css

The project was built assuming it is hosted at ./.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.

Find out more about deployment here:

  bit.ly/CRA-deploy

  • electron-builder  version=22.7.0 os=5.4.0-47-generic
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=canvas@2.6.1 platform=linux arch=x64
  • rebuilding native dependency  name=canvas version=2.6.1
  ⨯ cannot execute  cause=exit status 1
                    out=$ node-pre-gyp install --fallback-to-build
    Failed to execute '/home/linuxbrew/.linuxbrew/Cellar/node/14.10.1/bin/node /home/cdiesh/src/jbrowse-components/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/cdiesh/src/jbrowse-components/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/cdiesh/src/jbrowse-components/node_modules/canvas/build/Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v7.1' (1)
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

                    errorOut=node-pre-gyp info it worked if it ends with ok
    node-pre-gyp info using node-pre-gyp@0.11.0
    node-pre-gyp info using node@14.10.1 | linux | x64
    node-pre-gyp WARN Using request for node-pre-gyp https download
    node-pre-gyp http GET https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-electron-v7.1-linux-glibc-x64.tar.gz
    node-pre-gyp http 404 https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-electron-v7.1-linux-glibc-x64.tar.gz
    node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-electron-v7.1-linux-glibc-x64.tar.gz
    node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.1 and electron@7.1.0 (electron-v7.1 ABI, glibc) (falling back to source compile with node-gyp)
    node-pre-gyp http 404 status code downloading tarball https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-electron-v7.1-linux-glibc-x64.tar.gz
    gyp info it worked if it ends with ok
    gyp info using node-gyp@3.8.0
    gyp info using node@14.10.1 | linux | x64
    gyp info ok
    gyp info it worked if it ends with ok
    gyp info using node-gyp@3.8.0
    gyp info using node@14.10.1 | linux | x64
    gyp info spawn /usr/bin/python2
    gyp info spawn args [
    gyp info spawn args   '/home/cdiesh/src/jbrowse-components/node_modules/node-gyp/gyp/gyp_main.py',
    gyp info spawn args   'binding.gyp',
    gyp info spawn args   '-f',
    gyp info spawn args   'make',
    gyp info spawn args   '-I',
    gyp info spawn args   '/home/cdiesh/src/jbrowse-components/node_modules/canvas/build/config.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/home/cdiesh/src/jbrowse-components/node_modules/node-gyp/addon.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/home/cdiesh/.electron-gyp/7.1.0/include/node/common.gypi',
    gyp info spawn args   '-Dlibrary=shared_library',
    gyp info spawn args   '-Dvisibility=default',
    gyp info spawn args   '-Dnode_root_dir=/home/cdiesh/.electron-gyp/7.1.0',
    gyp info spawn args   '-Dnode_gyp_dir=/home/cdiesh/src/jbrowse-components/node_modules/node-gyp',
    gyp info spawn args   '-Dnode_lib_file=/home/cdiesh/.electron-gyp/7.1.0/<(target_arch)/node.lib',
    gyp info spawn args   '-Dmodule_root_dir=/home/cdiesh/src/jbrowse-components/node_modules/canvas',
    gyp info spawn args   '-Dnode_engine=v8',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.'
    gyp info spawn args ]
    Package pixman-1 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `pixman-1.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'pixman-1' found
    gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
    gyp ERR! configure error
    gyp ERR! stack Error: `gyp` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onCpExit (/home/cdiesh/src/jbrowse-components/node_modules/node-gyp/lib/configure.js:345:16)
    gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
    gyp ERR! System Linux 5.4.0-47-generic
    gyp ERR! command "/home/linuxbrew/.linuxbrew/Cellar/node/14.10.1/bin/node" "/home/cdiesh/src/jbrowse-components/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/cdiesh/src/jbrowse-components/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/home/cdiesh/src/jbrowse-components/node_modules/canvas/build/Release" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v7.1"
    gyp ERR! cwd /home/cdiesh/src/jbrowse-components/node_modules/canvas
    gyp ERR! node -v v14.10.1
    gyp ERR! node-gyp -v v3.8.0
    gyp ERR! not ok
    node-pre-gyp ERR! build error
    node-pre-gyp ERR! stack Error: Failed to execute '/home/linuxbrew/.linuxbrew/Cellar/node/14.10.1/bin/node /home/cdiesh/src/jbrowse-components/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/cdiesh/src/jbrowse-components/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/cdiesh/src/jbrowse-components/node_modules/canvas/build/Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v7.1' (1)
    node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/cdiesh/src/jbrowse-components/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
    node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
    node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1047:16)
    node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
    node-pre-gyp ERR! System Linux 5.4.0-47-generic
    node-pre-gyp ERR! command "/home/linuxbrew/.linuxbrew/Cellar/node/14.10.1/bin/node" "/home/cdiesh/src/jbrowse-components/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
    node-pre-gyp ERR! cwd /home/cdiesh/src/jbrowse-components/node_modules/canvas
    node-pre-gyp ERR! node -v v14.10.1
    node-pre-gyp ERR! node-pre-gyp -v v0.11.0
    node-pre-gyp ERR! not ok
    error Command failed with exit code 1.

                    command=/home/linuxbrew/.linuxbrew/Cellar/node/14.10.1/bin/node /usr/share/yarn/bin/yarn.js run install
                    workingDir=/home/cdiesh/src/jbrowse-components/node_modules/canvas

```

**Comment by cmdcolin** [comment]
I had to install these, with homebrew, to fix the above error

     brew install pixman cairo pango

didn't matter that those were installed already via apt...

**Comment by cmdcolin** [comment]
Also note: probably a good approach for building the app https://github.com/samuelmeuli/action-electron-builder
