### ISSUE TITLE
Error running yarn build on certain machines

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1377]
```
lerna ERR! yarn run build exited 1 in '@jbrowse/plugin-svg'
lerna ERR! yarn run build stdout:
$ tsdx build
✓ Creating entry file 7 secs
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:
Circular dependency: src/SvgFeatureRenderer/components/util.ts -> src/SvgFeatureRenderer/components/Chevron.js -> src/SvgFeatureRenderer/components/util.ts
Circular dependency: src/SvgFeatureRenderer/components/util.ts -> src/SvgFeatureRenderer/components/ProcessedTranscript.js -> src/SvgFeatureRenderer/components/util.ts
Circular dependency: src/SvgFeatureRenderer/components/util.ts -> src/SvgFeatureRenderer/components/Subfeatures.js -> src/SvgFeatureRenderer/components/util.ts
Circular dependency: src/SvgFeatureRenderer/components/util.ts -> src/SvgFeatureRenderer/components/Chevron.js -> src/SvgFeatureRenderer/components/util.ts
Circular dependency: src/SvgFeatureRenderer/components/util.ts -> src/SvgFeatureRenderer/components/ProcessedTranscript.js -> src/SvgFeatureRenderer/components/util.ts
Circular dependency: src/SvgFeatureRenderer/components/util.ts -> src/SvgFeatureRenderer/components/Subfeatures.js -> src/SvgFeatureRenderer/components/util.ts
Circular dependency: src/SvgFeatureRenderer/components/util.ts -> src/SvgFeatureRenderer/components/Chevron.js -> src/SvgFeatureRenderer/components/util.ts
Circular dependency: src/SvgFeatureRenderer/components/util.ts -> src/SvgFeatureRenderer/components/ProcessedTranscript.js -> src/SvgFeatureRenderer/components/util.ts
Circular dependency: src/SvgFeatureRenderer/components/util.ts -> src/SvgFeatureRenderer/components/Subfeatures.js -> src/SvgFeatureRenderer/components/util.ts
  202 |   ...handlers
  203 | }) {
> 204 |   const blockLayout = blockLayoutFeatures?.get(blockKey);
      |                                          ^ Unexpected token: punc (.)
  205 |
  206 |   if (!blockLayout) {
  207 |     return null;
(terser plugin) SyntaxError: Unexpected token: punc (.)
SyntaxError: Unexpected token: punc (.)
    at ee (/home/cdiesh/src/jbrowse-components2/node_modules/rollup-plugin-terser/node_modules/terser/dist/bundle.min.js:1:19541)
    at c (/home/cdiesh/src/jbrowse-components2/node_modules/rollup-plugin-terser/node_modules/terser/dist/bundle.min.js:1:28244)
    at l (/home/cdiesh/src/jbrowse-components2/node_modules/rollup-plugin-terser/node_modules/terser/dist/bundle.min.js:1:28335)
    at f (/home/cdiesh/src/jbrowse-components2/node_modules/rollup-plugin-terser/node_modules/terser/dist/bundle.min.js:1:28388)
    at G (/home/cdiesh/src/jbrowse-components2/node_modules/rollup-plugin-terser/node_modules/terser/dist/bundle.min.js:1:42202)
    at ge (/home/cdiesh/src/jbrowse-components2/node_modules/rollup-plugin-terser/node_modules/terser/dist/bundle.min.js:1:48272)
    at /home/cdiesh/src/jbrowse-components2/node_modules/rollup-plugin-terser/node_modules/terser/dist/bundle.min.js:1:49152
    at be (/home/cdiesh/src/jbrowse-components2/node_modules/rollup-plugin-terser/node_modules/terser/dist/bundle.min.js:1:49167)
    at ze (/home/cdiesh/src/jbrowse-components2/node_modules/rollup-plugin-terser/node_modules/terser/dist/bundle.min.js:1:50421)
    at qe (/home/cdiesh/src/jbrowse-components2/node_modules/rollup-plugin-terser/node_modules/terser/dist/bundle.min.js:1:50653)

error Command failed with exit code 1.

lerna ERR! yarn run build exited 1 in '@jbrowse/plugin-svg'
lerna WARN complete Waiting for 4 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

A similar error has happened during a release process, which performs a bunch of yarn builds

```
> @jbrowse/plugin-alignments@0.0.1-beta.20 prepack /home/cdiesh/src/jbrowse-components/plugins/alignments
> yarn build; yarn useDist

$ tsdx build
✓ Creating entry file 2.5 secs
⠼ Building modules
  893 |     }
  894 |
> 895 |     const highlightedFeature = featureIdUnderMouse || contextMenuFeature?.id();
      |                                                                         ^ Unexpected token: punc (.)
  896 |
  897 |     if (highlightedFeature && (blockLayout = blockLayoutFeatures.get(blockKey)) && (rect = blockLayout.get(highlightedFeature))) {
(terser plugin) SyntaxError: Unexpected token: punc (.)


```

Note that it did end up doing a full release of these even though I tried to halt it, but it appeared to be a somewhat successful publish despite this error

**Comment by cmdcolin** [comment]
Note that @garrettjstevens noted that it works on his machine, and it also works on travis, so there might be a unknown variable here. I could scrap my whole install and see...maybe low priority issue but just came up again trying to cut a release

**Comment by cmdcolin** [comment]
a weird hypothesis is that the parallelism of my machine could cause this?

**Comment by cmdcolin** [comment]
that doesn't really explain the specific error message I suppose. I tried on virtualmachine blank ubuntu instance and it worked. I have stripped my machine down to pretty bare bones and still get the error though

**Comment by cmdcolin** [comment]
I no longer have a build error, I did a full successful yarn build on my system

Maybe I'll just close for now

It is hard to say what was causing this for me, and I could try to git bisect to see if anything changed but we certainly didn't change the code it complained about which was the optional chaining, so it could just be a weird mystery...

I was pretty sparse in reporting my system setup but I have node 14.5.1 and believe i had this also when it was failing
