### ISSUE TITLE
Warning from test

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1605]
```
    console.error config/jest/console.js:10
      [
        'Error: Not implemented: HTMLFormElement.prototype.submit\n' +
          '    at module.exports (/home/cdiesh/src/jbrowse-components/node_modules/jest-environment-jsdom-fourteen/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)\n' +
          '    at HTMLFormElementImpl.submit (/home/cdiesh/src/jbrowse-components/node_modules/jest-environment-jsdom-fourteen/node_modules/jsdom/lib/jsdom/living/nodes/HTMLFormElement-impl.js:78:5)\n' +
          '    at HTMLFormElementImpl._doSubmit (/home/cdiesh/src/jbrowse-components/node_modules/jest-environment-jsdom-fourteen/node_modules/jsdom/lib/jsdom/living/nodes/HTMLFormElement-impl.js:70:10)\n' +
          '    at HTMLButtonElementImpl._activationBehavior (/home/cdiesh/src/jbrowse-components/node_modules/jest-environment-jsdom-fourteen/node_modules/jsdom/lib/jsdom/living/nodes/HTMLButtonElement-impl.js:23:14)\n' +
          '    at HTMLSpanElementImpl._dispatch (/home/cdiesh/src/jbrowse-components/node_modules/jest-environment-jsdom-fourteen/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:232:26)\n' +
          '    at HTMLSpanElementImpl.dispatchEvent (/home/cdiesh/src/jbrowse-components/node_modules/jest-environment-jsdom-fourteen/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)\n' +
          '    at HTMLSpanElement.dispatchEvent (/home/cdiesh/src/jbrowse-components/node_modules/jest-environment-jsdom-fourteen/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:144:23)\n' +
          '    at fireEvent (/home/cdiesh/src/jbrowse-components/node_modules/@testing-library/dom/dist/events.js:624:18)\n' +
          '    at Function.fireEvent.<computed> [as click] (/home/cdiesh/src/jbrowse-components/node_modules/@testing-library/dom/dist/events.js:690:36)\n' +
          '    at /home/cdiesh/src/jbrowse-components/node_modules/@testing-library/react/dist/pure.js:149:40',
        undefined
      ]


```

Can be seen here https://github.com/GMOD/jbrowse-components/runs/1659223582#step:5:33

**Comment by cmdcolin** [comment]
this is not longer happening in tests on github actions or locally from what i can tell, could maybe close for now
