### ISSUE TITLE
Trouble installing on node 15 due to node-canvas package

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1739]
When trying to use the dev package which uses @jbrowse/core I have trouble with the node-canvas package

It is now a pinned issue on the node-canvas repo https://github.com/Automattic/node-canvas/issues/1688

It may be that there is something also with the particular combination of python 3.9 and node 15 that disallows it building from non-binary but the result is I have to downgrade to node 14

```
~/s/j/p/jbrowse-web ❯❯❯ yarn                                                                                                                                          ✘ 130
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[##########################################################################################----------------------------------------------------------------------] 1808/3206t
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @jbrowse/core@1.0.3" has unmet peer dependency "@material-ui/data-grid@^4.0.0-alpha.10".
warning " > @jbrowse/core@1.0.3" has unmet peer dependency "@material-ui/lab@^4.0.0-alpha.45".
warning " > @jbrowse/plugin-linear-genome-view@1.0.3" has unmet peer dependency "@material-ui/lab@^4.0.0-alpha.45".
warning " > babel-loader@8.1.0" has unmet peer dependency "webpack@>=2".
warning " > @storybook/preset-create-react-app@3.1.5" has unmet peer dependency "@storybook/node-logger@*".
warning "@storybook/preset-create-react-app > react-docgen-typescript-plugin > react-docgen-typescript-loader > @webpack-contrib/schema-utils@1.0.0-beta.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
warning " > eslint-config-airbnb-typescript@7.2.1" has unmet peer dependency "@typescript-eslint/eslint-plugin@^2.24.0".
warning "eslint-config-airbnb-typescript > @typescript-eslint/parser@2.34.0" has unmet peer dependency "eslint@^5.0.0 || ^6.0.0".
warning "eslint-config-airbnb-typescript > eslint-config-airbnb@18.1.0" has unmet peer dependency "eslint@^5.16.0 || ^6.8.0".
warning "eslint-config-airbnb-typescript > eslint-config-airbnb@18.1.0" has unmet peer dependency "eslint-plugin-import@^2.20.1".
warning "eslint-config-airbnb-typescript > eslint-config-airbnb@18.1.0" has unmet peer dependency "eslint-plugin-jsx-a11y@^6.2.3".
warning "eslint-config-airbnb-typescript > eslint-config-airbnb@18.1.0" has unmet peer dependency "eslint-plugin-react@^7.19.0".
warning "eslint-config-airbnb-typescript > eslint-config-airbnb@18.1.0" has incorrect peer dependency "eslint-plugin-react-hooks@^2.5.0 || ^1.7.0".
warning "eslint-config-airbnb-typescript > eslint-config-airbnb-base@14.1.0" has unmet peer dependency "eslint@^5.16.0 || ^6.8.0".
warning "eslint-config-airbnb-typescript > eslint-config-airbnb-base@14.1.0" has unmet peer dependency "eslint-plugin-import@^2.20.1".
warning "eslint-config-airbnb-typescript > @typescript-eslint/parser > @typescript-eslint/experimental-utils@2.34.0" has unmet peer dependency "eslint@*".
warning " > eslint-config-prettier@6.11.0" has unmet peer dependency "eslint@>=3.14.1".
warning " > eslint-plugin-prettier@3.1.3" has unmet peer dependency "eslint@>= 5.0.0".
warning " > eslint-plugin-react-hooks@4.0.4" has unmet peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0".
warning " > jest-image-snapshot@3.1.0" has unmet peer dependency "jest@>=20 <=25".
warning " > webpack-cli@3.3.11" has unmet peer dependency "webpack@4.x.x".
warning " > worker-loader@2.0.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0-alpha.0 || ^4.0.0".
warning " > @jbrowse/plugin-dotplot-view@1.0.3" has unmet peer dependency "@material-ui/lab@^4.0.0-alpha.45".
warning " > @jbrowse/plugin-trackhub-registry@1.0.3" has unmet peer dependency "dompurify@^2.0.11".
warning "workspace-aggregator-691d6a23-a32a-4fbe-82e1-ec8c91df1ea5 > @jbrowse/plugin-alignments > react-d3-axis@0.1.2" has incorrect peer dependency "react@^15.0.0".
[4/4] Building fresh packages...
[1/9] ⠈ canvas
[-/9] ⠈ waiting...
[6/9] ⠈ electron
[4/9] ⠈ node-sass
error /home/cdiesh/src/jbrowse-components/node_modules/canvas: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: /home/cdiesh/src/jbrowse-components/node_modules/canvas
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.11.0
node-pre-gyp info using node@15.10.0 | linux | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "/home/cdiesh/src/jbrowse-components/node_modules/canvas/build/Release/canvas.node" (not found)
node-pre-gyp http GET https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v88-linux-glibc-x64.tar.gz
node-pre-gyp http 404 https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v88-linux-glibc-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v88-linux-glibc-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.1 and node@15.10.0 (node-v88 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v88-linux-glibc-x64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@15.10.0 | linux | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@15.10.0 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [
gyp info spawn args   '/home/cdiesh/src/jbrowse-components/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/cdiesh/src/jbrowse-components/node_modules/canvas/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/cdiesh/src/jbrowse-components/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/cdiesh/.node-gyp/15.10.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/cdiesh/.node-gyp/15.10.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/cdiesh/src/jbrowse-components/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/cdiesh/.node-gyp/15.10.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/cdiesh/src/jbrowse-components/node_modules/canvas',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Package pixman-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `pixman-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pixman-1' found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/cdiesh/src/jbrowse-components/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (node:events:378:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Linux 5.8.0-43-generic
gyp ERR! command "/home/cdiesh/.nvm/versions/node/v15.10.0/bin/node" "/home/cdiesh/src/jbrowse-components/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/cdiesh/src/jbrowse-components/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/home/cdiesh/src/jbrowse-components/node_modules/canvas/build/Release" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v88"
gyp ERR! cwd /home/cdiesh/src/jbrowse-components/node_modules/canvas
gyp ERR! node -v v15.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/home/cdiesh/.nvm/versions/node/v15.10.0/bin/node /home/cdiesh/src/jbrowse-components/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/cdiesh/src/jbrowse-components/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/cdiesh/src/jbrowse-components/node_modules/canvas/build/Release --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v88' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/cdiesh/src/jbrowse-components/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:378:20)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
node-pre-gyp ERR! System Linux 5.8.0-43-generic
node-pre-gyp ERR! command "/home/cdiesh/.nvm/versions/node/v15.10.0/bin/node" "/home/cdiesh/src/jbrowse-components/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/cdiesh/src/jbrowse-components/node_modules/canvas
node-pre-gyp ERR! node -v v15.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
```

**Comment by cmdcolin** [comment]
On the grand scheme of things this is not too urgent but it is notable, and this is a runtime dependency of @jbrowse/core has canvas dependency so it could affect consumers of our app

**Comment by cmdcolin** [comment]
It might have actually been that I use homebrew and had to homebrew install pixman cairo pango, and I was able to get it installed. I will leave this open perhaps because this does call into question if this is desirable to have a complicated install

**Comment by cmdcolin** [comment]
Recall the node-canvas is used for making snapshot tests of our canvases, and could be used at runtime for a node environment to render to canvas too

One possibility: we make node-canvas a peerDependency, and make the offscreenCanvasPolyfill just throw if canvas is not installed and it seems like it is trying to render to canvas in node environment, e.g. using require('canvas') at time of use in that file?

**Comment by cmdcolin** [comment]
may not be such an issue anymore but could continue to be a source of complicated in the future...could close for now though. look at #2280

**Comment by cmdcolin** [comment]
this issue may continue to cause pain...one option might be making canvas a peerDependency or an optionalDependency, and then only products that use it could have canvas actually listed

**Comment by cmdcolin** [comment]
just commenting because i cannot get it to install under the new node 18 (released today)

**Comment by cmdcolin** [comment]
possible alternatives may also exist

https://github.com/Brooooooklyn/Canvas
http://joshmarinacci.github.io/node-pureimage/

**Comment by cmdcolin** [comment]
now users should only run into this if they install a product that uses canvas, e.g. the main jbrowse-components repo dev environment (for snapshot tests) or @jbrowse/img :)
