### ISSUE TITLE
Some flaky tests on pileup image snapshots

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1797]
Seen on master branch builds

```
FAIL products/jbrowse-web/src/tests/Reload.test.js (27.002s)
  ● reload tests › reloads alignments track (BAM 404)

    Expected image to be the same size as the snapshot (1600x432), but was different (1600x90).
    See diff for details: /home/runner/work/jbrowse-components/jbrowse-components/products/jbrowse-web/src/tests/__image_snapshots__/__diff_output__/reload-test-js-reload-tests-reloads-alignments-track-bam-404-1-diff.png

      173 |     const pileupData = pileupImg.replace(/^data:image\/\w+;base64,/, '')
      174 |     const pileupBuf = Buffer.from(pileupData, 'base64')
    > 175 |     expect(pileupBuf).toMatchImageSnapshot({
          |                       ^
      176 |       failureThreshold: 0.05,
      177 |       failureThresholdType: 'percent',
      178 |     })

      at _callee8$ (products/jbrowse-web/src/tests/Reload.test.js:175:23)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:293:22)
      at Generator.next (node_modules/regenerator-runtime/runtime.js:118:21)
      at asyncGeneratorStep (node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
```

**Comment by cmdcolin** [comment]
Note, one surprising thing here is the dimensions of the snapshot, it says it got a snapshot that was 432 pixels high, however, it is specifically testing a SNPCoverage track which has height 45 (height *2 for high resolution displays on retina)===90px

It is surprising that it would get a 432 height track when this specific track is testing volvox_bam_snpcoverage(?)

**Comment by cmdcolin** [comment]
Seen again https://github.com/GMOD/jbrowse-components/runs/2099377742?check_suite_focus=true#step:5:44

Tests seem to be getting pretty flaky in general...
