### ISSUE TITLE
Alignments track integration test failing on node 15 (possibly not node version related)

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#1876]
```
~  node --version
v15.10.0
~  yarn --version
1.22.10
```

Errors

```
yarn test products/jbrowse-web/src/tests/Alignments.test.js                                          ✘ 1
yarn run v1.22.10
$ DEBUG_PRINT_LIMIT=0 jest products/jbrowse-web/src/tests/Alignments.test.js
  console.error config/jest/console.js:10
    [
      'Warning: `NaN` is an invalid value for the `%s` css style property.%s',
      'top',
      '\n' +
        '    in div (at LinearBlocks.tsx:57)\n' +
        '    in div (at Block.tsx:49)\n' +
        '    in wrappedComponent (at LinearBlocks.tsx:49)\n' +
        '    in wrappedComponent (at LinearBlocks.tsx:107)\n' +
        '    in div (at LinearBlocks.tsx:100)\n' +
        '    in LinearBlocks (at BaseLinearDisplay.tsx:85)\n' +
        '    in div (at BaseLinearDisplay.tsx:61)\n' +
        '    in wrappedComponent (at AlignmentsDisplay.tsx:43)\n' +
        '    in div (at AlignmentsDisplay.tsx:34)\n' +
        '    in div (at AlignmentsDisplay.tsx:10)\n' +
        '    in wrappedComponent (at TrackContainer.tsx:128)\n' +
        '    in div (at TrackContainer.tsx:123)\n' +
        '    in div (created by ForwardRef(Paper))\n' +
        '    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))\n' +
        '    in WithStyles(ForwardRef(Paper)) (at TrackContainer.tsx:111)\n' +
        '    in div (at TrackContainer.tsx:98)\n' +
        '    in TrackContainer (at LinearGenomeView.tsx:106)\n' +
        '    in div (at TracksContainer.tsx:169)\n' +
        '    in TracksContainer (at LinearGenomeView.tsx:90)\n' +
        '    in div (at LinearGenomeView.tsx:46)\n' +
        '    in wrappedComponent (at App.js:158)\n' +
        '    in div (created by ForwardRef(Paper))\n' +
        '    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))\n' +
        '    in WithStyles(ForwardRef(Paper)) (at ViewContainer.tsx:227)\n' +
        '    in div (created by ForwardRef(Paper))\n' +
        '    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))\n' +
        '    in WithStyles(ForwardRef(Paper)) (at ViewContainer.tsx:173)\n' +
        '    in wrappedComponent (created by WithContentRect)\n' +
        '    in WithContentRect (at App.js:153)\n' +
        '    in div (at App.js:145)\n' +
        '    in div (at App.js:112)\n' +
        '    in div (at App.js:104)\n' +
        '    in App (at JBrowse.js:74)\n' +
        '    in ThemeProvider (at JBrowse.js:72)\n' +
        '    in wrappedComponent (at Alignments.test.js:254)\n' +
        '    in StylesProvider (at react.js:9)'
    ]

 FAIL  products/jbrowse-web/src/tests/Alignments.test.js (27.232s)
  alignments track
    ✓ opens an alignments track (7141ms)
    ✓ opens the track menu and enables soft clipping (4840ms)
    ✓ selects a sort, updates object and layout (2315ms)
    ✓ selects a color, updates object and layout (2101ms)
    ✓ colors by tag, updates object and layout (2749ms)
    ✓ test that bam with small max height displays message (2227ms)
    ✕ test snpcoverage doesnt count snpcoverage (2104ms)

  ● alignments track › test snpcoverage doesnt count snpcoverage

    TypeError: Cannot read property 'toDataURL' of undefined

      300 |       Buffer.from(
      301 |         snpCoverageCanvas[1]
    > 302 |           .toDataURL()
          |            ^
      303 |           .replace(/^data:image\/\w+;base64,/, ''),
      304 |         'base64',
      305 |       ),

      at _callee7$ (products/jbrowse-web/src/tests/Alignments.test.js:302:12)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:293:22)
      at Generator.next (node_modules/regenerator-runtime/runtime.js:118:21)
      at asyncGeneratorStep (node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 6 passed, 7 total
Snapshots:   7 passed, 7 total
Time:        28.809s, estimated 52s
Ran all test suites matching /products\/jbrowse-web\/src\/tests\/Alignments.test.js/i.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.


```

appeares to happen on github actions if i bump our version to 15 too https://github.com/GMOD/jbrowse-components/runs/2266959178?check_suite_focus=true#step:5:62

**Comment by cmdcolin** [comment]
Also happened here on node 10? https://github.com/GMOD/jbrowse-components/pull/1875
