### ISSUE TITLE
while running jbrowse text-index: events.js:174, unhandled error

### ISSUE THREAD

**Issue by lennartraman** [GMOD/jbrowse-components#2360]
Whenever I run `jbrowse text-index --out path/to/jbrowse2`, I get following error:

```
root@ea95d858738a:/jbrowse2# jbrowse text-index --out /jbrowse2                                      
Indexing assembly Aspergillus oryzae RIB40...
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ NCBI-AspOry-RIB40 0% | ETA: 0sevents.js:174
      throw er; // Unhandled 'error' event
      ^

TypeError: Object.fromEntries is not a function
    at Object.indexGff3_1 (/usr/local/lib/node_modules/@jbrowse/cli/lib/types/gff3Adapter.js:60:46)
    at indexGff3_1.next (<anonymous>)
    at resume (/usr/local/lib/node_modules/@jbrowse/cli/node_modules/tslib/tslib.js:208:48)
    at fulfill (/usr/local/lib/node_modules/@jbrowse/cli/node_modules/tslib/tslib.js:210:35)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Some additional info
- I'm running jbrowse/cli/1.4.4 (upgraded using `jbrowse upgrade`) inside a Docker container.
- I have 4 different gff files in my config.json file.
- Specifying a gff with the `--tracks` option results in the same error for each gff.
- My gff files have both Name and ID attributes in the gene rows.
- There is a symbolic link within the jbrowse folder that links a mounted data folder (containing all fna, gff, bam, wig, ... files), which has worked fine.

Any idea what triggers this error and how it might be fixed?

Thanks! Lennart

**Comment by cmdcolin** [comment]
basically you would want to upgrade your node.js version to v12 or later

node v10 is EOL (end of life) but we could consider adding support back for it

recently asked here too
https://github.com/GMOD/jbrowse-components/discussions/2359
