### ISSUE TITLE
Possible flaky authentication test

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#2470]
I have seen this locally also

Failed on latest main branch

https://github.com/GMOD/jbrowse-components/runs/4040254321?check_suite_focus=true#step:5:12313

**Comment by peterkxie** [comment]
not sure of the cause, i'll look into it more

**Comment by cmdcolin** [comment]
one thing i see, can be caught pretty consistently running 

yarn test products/jbrowse-web/src/tests/Authentication.test.js 


```
$ jest products/jbrowse-web/src/tests/Authentication.test.js
 FAIL  products/jbrowse-web/src/tests/Authentication.test.js (9.248 s)
  authentication
    ✓ open a bigwig track that needs oauth authentication and has existing token (1857 ms)
    ✓ opens a bigwig track that needs external token authentication (1903 ms)
    ✕ opens a bigwig track that needs httpbasic authentication (1766 ms)

  ● authentication › opens a bigwig track that needs httpbasic authentication

    Expected image to match or be a close match to snapshot but was 12.992500000000001% different from snapshot (41576 differing pixels).
    See diff for details: /home/cdiesh/src/jbrowse-components/products/jbrowse-web/src/tests/__image_snapshots__/__diff_output__/authentication-test-js-authentication-opens-a-bigwig-track-that-needs-httpbasic-authentication-1-diff.png

      205 |     const bigwigData = bigwigImg.replace(/^data:image\/\w+;base64,/, '')
      206 |     const bigwigBuf = Buffer.from(bigwigData, 'base64')
    > 207 |     expect(bigwigBuf).toMatchImageSnapshot({
          |                       ^
      208 |       failureThreshold: 0.05,
      209 |       failureThresholdType: 'percent',
      210 |     })

      at _callee3$ (products/jbrowse-web/src/tests/Authentication.test.js:207:23)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:294:22)
      at Generator.next (node_modules/regenerator-runtime/runtime.js:119:21)
      at asyncGeneratorStep (node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)

 › 1 snapshot failed.
  console.error
    TypeError: Cannot read properties of undefined (reading 'ok')
        at RemoteFile._callee3$ (/home/cdiesh/src/jbrowse-components/node_modules/generic-filehandle/src/remoteFile.ts:117:19)
        at tryCatch (/home/cdiesh/src/jbrowse-components/node_modules/regenerator-runtime/runtime.js:63:40)
        at Generator.invoke [as _invoke] (/home/cdiesh/src/jbrowse-components/node_modules/regenerator-runtime/runtime.js:294:22)
        at Generator.next (/home/cdiesh/src/jbrowse-components/node_modules/regenerator-runtime/runtime.js:119:21)
        at asyncGeneratorStep (/home/cdiesh/src/jbrowse-components/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
        at _next (/home/cdiesh/src/jbrowse-components/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)


```

I think that the fetch reimplementation by the auth system is returning undefined from fetch, so checking response.ok fails

**Comment by cmdcolin** [comment]
would be good to get this one fixed....seems to happen still
