### ISSUE TITLE
SVG export fails when rasterization is off

### ISSUE THREAD

**Issue by AlbatrosHurleur** [GMOD/jbrowse-components#3046]
I get a `TypeError: o.indexOf is not a function` message when exporting SVG if rasterization is turned off (or not supported in the browser).

**To Reproduce**

Click on "export SVG" button
Untick "Rasterize canvas based tracks"
Click "Submit"

**Expected behavior**

A SVG file is downloaded

**Screenshots**

On Firefox 101.0.1:
![image](https://user-images.githubusercontent.com/48366457/174774342-6b746c4a-ba9d-4ad8-97eb-e698b35d30e1.png)

On Chromium 102.0.5005.61:
![image](https://user-images.githubusercontent.com/48366457/174775173-75978f42-38b9-4479-94f0-4e4bfefeb927.png)

**Version:**
Jbrowse 1.7.10 (Web)

**Comment by cmdcolin** [comment]
>Is there any test I could do to see what is triggering this? Or maybe you would like to get the data to reproduce?


if you go the the developer console (https://javascript.info/devtools) it might give a more complete stack trace for that error, if you want to screenshot or paste it here it may have some clues!

**Comment by cmdcolin** [comment]
do you have any custom coloring or color callbacks on the quantitative tracks? trying to think if there is a reason why rasterization off would fail and looking in the canvas2svg library code for indexOf

**Comment by AlbatrosHurleur** [comment]
> if you go the the developer console (https://javascript.info/devtools) it might give a more complete stack trace for that error, if you want to screenshot or paste it here it may have some clues!

```
ExportSvgDialog.tsx:107 TypeError: o.indexOf is not a function
    at r.__applyStyleToCurrentElement (canvas2svg.js:360:90)
    at r.fillRect (canvas2svg.js:748:14)
    at r.value (CanvasAtom.js:78:5)
    at CanvasSequence.js:134:43
    at Array.forEach (<anonymous>)
    at r.value (CanvasSequence.js:134:28)
    at ServerSideRendererType.tsx:185:11
    at f (regeneratorRuntime.js:86:17)
    at Generator._invoke (regeneratorRuntime.js:66:24)
    at Generator.next (regeneratorRuntime.js:117:21)
```

>do you have any custom coloring or color callbacks on the quantitative tracks? trying to think if there is a reason why rasterization off would fail and looking in the canvas2svg library code for indexOf

I do have custom coloring:

```
            "XYPlotRenderer": {
              "type": "XYPlotRenderer",
              "posColor": "#DC3220",
              "negColor": "#005AB5",
              "displayCrossHatches": true
            }
```
I added one of the track giving the error without any customization, and it produced the same error.

**Comment by cmdcolin** [comment]
that is quite weird, i am not sure I'm able to reproduce it the right way.  I found a somewhat similar reproducition if I do something awkward, namely returning an object from a jexl callback for feature color (which would be sort of a non-sense operation), and that could reproduce the indexOf error during non-rasterized svg export, but that is not what you describe

```
{
      "type": "QuantitativeTrack",
      "trackId": "error",
      "name": "Track that errors in svg export",
      "assemblyNames": ["volvox"],
      "adapter": {
        "type": "BigWigAdapter",
        "bigWigLocation": {
          "locationType": "UriLocation",
          "uri": "volvox_microarray_posneg.bw",
          "baseUri": "http://localhost:3000/test_data/volvox/config.json"
        }
      },
      "displays": [
        {
          "type": "LinearWiggleDisplay",
          "displayId": "jdYHuGnpAc_-LinearWiggleDisplay-1655926888022",
          "renderers": {
            "XYPlotRenderer": {
              "type": "XYPlotRenderer",
              "negColor": "jexl:{error:'error'}"
            }
          }
        }
      ]
    },
```
That produces same indexOf error...

If you are able to share config and data file it may help narrow it down more

**Comment by AlbatrosHurleur** [comment]
I prepared a minimal config and data (genome + quantitative track) that can reproduce the issue on my side; I just sent you the download link by e-mail.

**Comment by cmdcolin** [comment]
@AlbatrosHurleur thanks so much for the reproducible case, added a fix here https://github.com/GMOD/jbrowse-components/pull/3057

will hopefully be released soon :)

**Comment by AlbatrosHurleur** [comment]
Glad it helped!

Thanks a lot for the fix.
