### ISSUE TITLE
Cannot change display type on lgv

### ISSUE THREAD

**Issue by carolinebridge-oicr** [GMOD/jbrowse-components#3121]
Cannot change the display type on a linear genome view.

v2.1.0, noticed on web.

Haven't extensively tested, but based on where it's happening in the code I assume this is all displays.

Noticed when trying to change the display type on an alignments track:

```
react-dom.production.min.js:101 Uncaught TypeError: Cannot read properties of undefined (reading 'displayId')
    at BaseTrackModel.ts:128:57
    at observablearray.ts:558:29
    at Array.findIndex (<anonymous>)
    at Proxy.<anonymous> (observablearray.ts:557:31)
    at Object.replaceDisplay (BaseTrackModel.ts:128:35)
    at Le (action.ts:68:19)
    at bound replaceDisplay (action.ts:49:16)
    at mobx-state-tree.module.js:3254:35
    at Te (mobx-state-tree.module.js:3097:16)
    at Proxy.n (mobx-state-tree.module.js:3124:16)
```

function `replaceDisplay` line 128 `const idx = self.displays.findIndex(d => d.conf.displayId === oldId)` in `BaseTrackModel.ts`

**Comment by garrettjstevens** [comment]
I think this will be fixed with https://github.com/GMOD/jbrowse-components/pull/3120
