### ISSUE TITLE
Storybook error after upgrading deps

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#3258]
It's good for the main branch to be able to be "upgradable" IMO, e.g. just keep testing that things work after yarn upgrades which gets minor/patch release, but currently if `yarn upgrade` is run on main, the storybook fails
https://github.com/GMOD/jbrowse-components/tree/upgrade_deps

```
$ yarn storybook:build
yarn run v1.22.18
$ build-storybook --quiet --static-dir public
info @storybook/react v6.5.12
info
info => Cleaning outputDir: /home/cdiesh/src/jbrowse-components/products/jbrowse-react-linear-genome-view/storybook-static
(node:2929000) DeprecationWarning: --static-dir CLI flag is deprecated, see:

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated---static-dir-cli-flag
(Use `node --trace-deprecation ...` to show where the warning was created)
info => Loading presets
info => Copying static files: ./public => ./
info => Compiling manager..
info => Compiling preview..
info Addon-docs: using MDX1
info => Using implicit CSS loaders
info => Using default Webpack5 setup
info => Manager built (34 s)
DeprecationWarning: 'createIdentifier' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: '' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createLiteral' has been deprecated since v4.0.0. Use `factory.createStringLiteral`, `factory.createStringLiteralFromNode`, `factory.createNumericLiteral`, `factory.createBigIntLiteral`, `factory.createTrue`, `factory.createFalse`, or the factory supplied by your transformation context instead.
DeprecationWarning: 'createBinaryExpression' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createExpressionStatement' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createPropertyAssignment' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createObjectLiteralExpression' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createExpressionStatement' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createTypeOfExpression' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createElementAccessExpression' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createIfStatement' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createBlock' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createVariableDeclaration' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createCatchClause' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createTryStatement' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createNull' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createTrue' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createFalse' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
DeprecationWarning: 'createArrayLiteralExpression' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
ERR! => Failed to build the preview
ERR! Module build failed (from ../../node_modules/babel-loader/lib/index.js):
ERR! TypeError: /home/cdiesh/src/jbrowse-components/packages/core/pluggableElementTypes/renderers/RendererType.ts: Cannot read properties of undefined (reading 'start')
ERR!     at Generator._printComments (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:667:48)
ERR!     at Generator._printLeadingComments (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:530:10)
ERR!     at Generator.print (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:403:10)
ERR!     at Generator.ObjectProperty (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/generators/types.js:98:8)
ERR!     at Buffer.exactSource (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/buffer.js:284:5)
ERR!     at Generator.exactSource (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:178:15)
ERR!     at Generator.print (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:406:10)
ERR!     at Generator.printJoin (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:479:12)
ERR!     at Generator.printList (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:554:17)
ERR!     at Generator.ObjectExpression (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/generators/types.js:56:10)
ERR!     at Buffer.exactSource (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/buffer.js:284:5)
ERR!     at Generator.exactSource (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:178:15)
ERR!     at Generator.print (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:406:10)
ERR!     at Generator.printJoin (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:479:12)
ERR!     at Generator.printList (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:554:17)
ERR!     at Generator.CallExpression (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/generators/expressions.js:216:8)
ERR!     at Generator.exactSource (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:174:22)
ERR!     at Generator.print (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:406:10)
ERR!     at Generator.printTerminatorless (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:359:12)
ERR!     at printStatementAfterKeyword (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/generators/statements.js:161:13)
ERR!     at Generator.ReturnStatement (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/generators/statements.js:179:3)
ERR!     at Generator.exactSource (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:174:22)
ERR!     at Generator.print (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:406:10)
ERR!     at Generator.printJoin (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:479:12)
ERR!     at Generator.printSequence (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:546:17)
ERR!     at Generator.SwitchCase (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/generators/statements.js:261:10)
ERR!     at Generator.exactSource (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:174:22)
ERR!     at Generator.print (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:406:10)
ERR!     at Generator.printJoin (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:479:12)
ERR!     at Generator.printSequence (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:546:17)
ERR!     at Generator.SwitchStatement (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/generators/statements.js:237:8)
ERR!     at Generator.exactSource (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:174:22)
ERR!     at Generator.print (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:406:10)
ERR!     at Generator.printJoin (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:479:12)
ERR!     at Generator.printSequence (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:546:17)
ERR!     at Generator.BlockStatement (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/generators/base.js:65:8)
ERR!     at Generator.exactSource (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:174:22)
ERR!     at Generator.print (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:406:10)
ERR!     at Generator.printBlock (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:514:10)
ERR!     at Generator.WhileStatement (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/generators/statements.js:117:8)
ERR!     at Generator.exactSource (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:174:22)
ERR!     at Generator.print (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:406:10)
ERR!     at Generator.printJoin (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:479:12)
ERR!     at Generator.printSequence (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:546:17)
ERR!     at Generator.BlockStatement (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/generators/base.js:65:8)
ERR!     at Generator.exactSource (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:174:22)
ERR!     at Generator.print (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:406:10)
ERR!     at Generator.FunctionExpression (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/generators/methods.js:127:8)
ERR!     at Generator.exactSource (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:174:22)
ERR!     at Generator.print (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:406:10)
ERR! Module build failed (from ../../node_modules/babel-loader/lib/index.js):
ERR! TypeError: /home/cdiesh/src/jbrowse-components/plugins/linear-genome-view/src/BaseLinearDisplay/models/BaseLinearDisplayModel.tsx: Cannot read properties of undefined (reading 'start')
ERR!     at Generator._printComments (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:667:48)
ERR!     at Generator._printLeadingComments (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:530:10)
ERR!     at Generator.print (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:403:10)
ERR!     at Generator.ObjectProperty (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/generators/types.js:98:8)
ERR!     at Buffer.exactSource (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/buffer.js:284:5)
ERR!     at Generator.exactSource (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:178:15)
ERR!     at Generator.print (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:406:10)
ERR!     at Generator.printJoin (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:479:12)
ERR!     at Generator.printList (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:554:17)
ERR!     at Generator.ObjectExpression (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/generators/types.js:56:10)
ERR!     at Buffer.exactSource (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/buffer.js:284:5)
ERR!     at Generator.exactSource (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:178:15)
ERR!     at Generator.print (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:406:10)
ERR!     at Generator.printTerminatorless (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:359:12)
ERR!     at printStatementAfterKeyword (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/generators/statements.js:161:13)
ERR!     at Generator.ReturnStatement (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/generators/statements.js:179:3)
ERR!     at Buffer.exactSource (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/buffer.js:284:5)
ERR!     at Generator.exactSource (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:178:15)
ERR!     at Generator.print (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:406:10)
ERR!     at Generator.printJoin (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:479:12)
ERR!     at Generator.printSequence (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:546:17)
ERR!     at Generator.BlockStatement (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/generators/base.js:65:8)
ERR!     at Buffer.exactSource (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/buffer.js:284:5)
ERR!     at Generator.exactSource (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:178:15)
ERR!     at Generator.print (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:406:10)
ERR!     at Generator.printAndIndentOnComments (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:503:10)
ERR!     at Generator.IfStatement (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/generators/statements.js:58:8)
ERR!     at Buffer.exactSource (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/buffer.js:284:5)
ERR!     at Generator.exactSource (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:178:15)
ERR!     at Generator.print (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:406:10)
ERR!     at Generator.printJoin (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:479:12)
ERR!     at Generator.printSequence (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:546:17)
ERR!     at Generator.BlockStatement (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/generators/base.js:65:8)
ERR!     at Buffer.exactSource (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/buffer.js:284:5)
ERR!     at Generator.exactSource (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:178:15)
ERR!     at Generator.print (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:406:10)
ERR!     at Generator.FunctionExpression (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/generators/methods.js:127:8)
ERR!     at Buffer.exactSource (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/buffer.js:284:5)
ERR!     at Generator.exactSource (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:178:15)
ERR!     at Generator.print (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:406:10)
ERR!     at Generator.printJoin (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:479:12)
ERR!     at Generator.printList (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:554:17)
ERR!     at Generator.CallExpression (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/generators/expressions.js:216:8)
ERR!     at Buffer.exactSource (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/buffer.js:284:5)
ERR!     at Generator.exactSource (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:178:15)
ERR!     at Generator.print (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:406:10)
ERR!     at Generator.printJoin (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:479:12)
ERR!     at Generator.printList (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:554:17)
ERR!     at Generator.CallExpression (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/generators/expressions.js:216:8)
ERR!     at Buffer.exactSource (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/buffer.js:284:5)
ERR! Module build failed (from ../../node_modules/babel-loader/lib/index.js):
ERR! TypeError: /home/cdiesh/src/jbrowse-components/plugins/linear-genome-view/src/LinearGenomeView/components/LinearGenomeViewSvg.tsx: Cannot read properties of undefined (reading 'start')
ERR!     at Generator._printComments (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:667:48)
ERR!     at Generator._printLeadingComments (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:530:10)
ERR!     at Generator.print (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:403:10)
ERR!     at Generator.printJoin (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:479:12)
ERR!     at Generator.printList (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:554:17)
ERR!     at Generator.CallExpression (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/generators/expressions.js:216:8)
ERR!     at Buffer.exactSource (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/buffer.js:284:5)
ERR!     at Generator.exactSource (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:178:15)
ERR!     at Generator.print (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:406:10)
ERR!     at Generator.printJoin (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:479:12)
ERR!     at Generator.printList (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:554:17)
ERR!     at Generator.CallExpression (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/generators/expressions.js:216:8)
ERR!     at Generator.exactSource (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:174:22)
ERR!     at Generator.print (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:406:10)
ERR!     at Generator.printTerminatorless (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:359:12)
ERR!     at printStatementAfterKeyword (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/generators/statements.js:161:13)
ERR!     at Generator.ReturnStatement (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/generators/statements.js:179:3)
ERR!     at Generator.exactSource (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:174:22)
ERR!     at Generator.print (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:406:10)
ERR!     at Generator.printJoin (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:479:12)
ERR!     at Generator.printSequence (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:546:17)
ERR!     at Generator.SwitchCase (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/generators/statements.js:261:10)
ERR!     at Generator.exactSource (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:174:22)
ERR!     at Generator.print (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:406:10)
ERR!     at Generator.printJoin (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:479:12)
ERR!     at Generator.printSequence (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:546:17)
ERR!     at Generator.SwitchStatement (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/generators/statements.js:237:8)
ERR!     at Generator.exactSource (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:174:22)
ERR!     at Generator.print (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:406:10)
ERR!     at Generator.printJoin (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:479:12)
ERR!     at Generator.printSequence (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:546:17)
ERR!     at Generator.BlockStatement (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/generators/base.js:65:8)
ERR!     at Generator.exactSource (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:174:22)
ERR!     at Generator.print (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:406:10)
ERR!     at Generator.printBlock (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:514:10)
ERR!     at Generator.WhileStatement (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/generators/statements.js:117:8)
ERR!     at Generator.exactSource (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:174:22)
ERR!     at Generator.print (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:406:10)
ERR!     at Generator.printJoin (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:479:12)
ERR!     at Generator.printSequence (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:546:17)
ERR!     at Generator.BlockStatement (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/generators/base.js:65:8)
ERR!     at Generator.exactSource (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:174:22)
ERR!     at Generator.print (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:406:10)
ERR!     at Generator.FunctionExpression (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/generators/methods.js:127:8)
ERR!     at Generator.exactSource (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:174:22)
ERR!     at Generator.print (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:406:10)
ERR!     at Generator.printJoin (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:479:12)
ERR!     at Generator.printList (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:554:17)
ERR!     at Generator.CallExpression (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/generators/expressions.js:216:8)
ERR!     at Generator.exactSource (/home/cdiesh/src/jbrowse-components/node_modules/@babel/generator/lib/printer.js:174:22)
ERR! Error: => Webpack failed, learn more with --debug-webpack
ERR!     at /home/cdiesh/src/jbrowse-components/node_modules/@storybook/builder-webpack5/dist/cjs/index.js:234:62
ERR!     at /home/cdiesh/src/jbrowse-components/node_modules/webpack/lib/HookWebpackError.js:68:3
ERR!     at Hook.eval [as callAsync] (eval at create (/home/cdiesh/src/jbrowse-components/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
ERR!     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/cdiesh/src/jbrowse-components/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
ERR!     at Cache.shutdown (/home/cdiesh/src/jbrowse-components/node_modules/webpack/lib/Cache.js:150:23)
ERR!     at /home/cdiesh/src/jbrowse-components/node_modules/webpack/lib/Compiler.js:1225:15
ERR!     at Hook.eval [as callAsync] (eval at create (/home/cdiesh/src/jbrowse-components/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
ERR!     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/cdiesh/src/jbrowse-components/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
ERR!     at Compiler.close (/home/cdiesh/src/jbrowse-components/node_modules/webpack/lib/Compiler.js:1218:23)
ERR!     at /home/cdiesh/src/jbrowse-components/node_modules/@storybook/builder-webpack5/dist/cjs/index.js:233:20
ERR!     at finalCallback (/home/cdiesh/src/jbrowse-components/node_modules/webpack/lib/Compiler.js:441:32)
ERR!     at /home/cdiesh/src/jbrowse-components/node_modules/webpack/lib/Compiler.js:458:13
ERR!     at Hook.eval [as callAsync] (eval at create (/home/cdiesh/src/jbrowse-components/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
ERR!     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/cdiesh/src/jbrowse-components/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
ERR!     at onCompiled (/home/cdiesh/src/jbrowse-components/node_modules/webpack/lib/Compiler.js:456:21)
ERR!     at /home/cdiesh/src/jbrowse-components/node_modules/webpack/lib/Compiler.js:1196:17
ERR!     at Hook.eval [as callAsync] (eval at create (/home/cdiesh/src/jbrowse-components/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
ERR!     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/cdiesh/src/jbrowse-components/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
ERR!     at /home/cdiesh/src/jbrowse-components/node_modules/webpack/lib/Compiler.js:1192:33
ERR!     at finalCallback (/home/cdiesh/src/jbrowse-components/node_modules/webpack/lib/Compilation.js:2787:11)
ERR!     at /home/cdiesh/src/jbrowse-components/node_modules/webpack/lib/Compilation.js:3092:11
ERR!     at Hook.eval [as callAsync] (eval at create (/home/cdiesh/src/jbrowse-components/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
ERR!     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/cdiesh/src/jbrowse-components/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
ERR!     at /home/cdiesh/src/jbrowse-components/node_modules/webpack/lib/Compilation.js:3085:38
ERR!     at eval (eval at create (/home/cdiesh/src/jbrowse-components/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:17:1)
ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
ERR!  Error: => Webpack failed, learn more with --debug-webpack
ERR!     at /home/cdiesh/src/jbrowse-components/node_modules/@storybook/builder-webpack5/dist/cjs/index.js:234:62
ERR!     at /home/cdiesh/src/jbrowse-components/node_modules/webpack/lib/HookWebpackError.js:68:3
ERR!     at Hook.eval [as callAsync] (eval at create (/home/cdiesh/src/jbrowse-components/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
ERR!     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/cdiesh/src/jbrowse-components/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
ERR!     at Cache.shutdown (/home/cdiesh/src/jbrowse-components/node_modules/webpack/lib/Cache.js:150:23)
ERR!     at /home/cdiesh/src/jbrowse-components/node_modules/webpack/lib/Compiler.js:1225:15
ERR!     at Hook.eval [as callAsync] (eval at create (/home/cdiesh/src/jbrowse-components/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
ERR!     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/cdiesh/src/jbrowse-components/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
ERR!     at Compiler.close (/home/cdiesh/src/jbrowse-components/node_modules/webpack/lib/Compiler.js:1218:23)
ERR!     at /home/cdiesh/src/jbrowse-components/node_modules/@storybook/builder-webpack5/dist/cjs/index.js:233:20
ERR!     at finalCallback (/home/cdiesh/src/jbrowse-components/node_modules/webpack/lib/Compiler.js:441:32)
ERR!     at /home/cdiesh/src/jbrowse-components/node_modules/webpack/lib/Compiler.js:458:13
ERR!     at Hook.eval [as callAsync] (eval at create (/home/cdiesh/src/jbrowse-components/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
ERR!     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/cdiesh/src/jbrowse-components/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
ERR!     at onCompiled (/home/cdiesh/src/jbrowse-components/node_modules/webpack/lib/Compiler.js:456:21)
ERR!     at /home/cdiesh/src/jbrowse-components/node_modules/webpack/lib/Compiler.js:1196:17
ERR!     at Hook.eval [as callAsync] (eval at create (/home/cdiesh/src/jbrowse-components/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
ERR!     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/cdiesh/src/jbrowse-components/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
ERR!     at /home/cdiesh/src/jbrowse-components/node_modules/webpack/lib/Compiler.js:1192:33
ERR!     at finalCallback (/home/cdiesh/src/jbrowse-components/node_modules/webpack/lib/Compilation.js:2787:11)
ERR!     at /home/cdiesh/src/jbrowse-components/node_modules/webpack/lib/Compilation.js:3092:11
ERR!     at Hook.eval [as callAsync] (eval at create (/home/cdiesh/src/jbrowse-components/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
ERR!     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/cdiesh/src/jbrowse-components/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
ERR!     at /home/cdiesh/src/jbrowse-components/node_modules/webpack/lib/Compilation.js:3085:38
ERR!     at eval (eval at create (/home/cdiesh/src/jbrowse-components/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:17:1)
ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
info => Loading presets
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by cmdcolin** [comment]
the deprecation warnings may be related to https://github.com/hipstersmoothie/react-docgen-typescript-plugin/issues/69 but those have been logging in the console for awhile, the error is likely something different

**Comment by cmdcolin** [comment]
probably related to https://github.com/babel/babel/pull/15031

**Comment by cmdcolin** [comment]
likely close
