### ISSUE TITLE
JBrowse.test.js "expects zoom in message" logs a mobx-state-tree warning

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#375]
```
     valid file tests
    ✓ opens reference sequence track and expects zoom in message (704ms)

  console.warn node_modules/mobx-state-tree/dist/mobx-state-tree.js:3007
    Error: [mobx-state-tree] You are trying to read or write to an object that is no longer part of a state tree. (Object type was 'AnonymousModel'). Either detach nodes first, or don't use objects after removing / replacing them in the tree.
        at warnError (/home/cdiesh/src/jbrowse-components/node_modules/mobx-state-tree/dist/mobx-state-tree.js:3007:18)
        at ObjectNode$$1.Object.<anonymous>.ObjectNode$$1.assertAlive (/home/cdiesh/src/jbrowse-components/node_modules/mobx-state-tree/dist/mobx-state-tree.js:1443:21)
        at ObservableValue.ObjectNode$$1._this.unbox [as dehancer] (/home/cdiesh/src/jbrowse-components/node_modules/mobx-state-tree/dist/mobx-state-tree.js:1237:23)
        at ObservableValue.Object.<anonymous>.ObservableValue.dehanceValue (/home/cdiesh/src/jbrowse-components/node_modules/mobx/lib/mobx.js:717:25)
        at ObservableValue.Object.<anonymous>.ObservableValue.get (/home/cdiesh/src/jbrowse-components/node_modules/mobx/lib/mobx.js:769:21)
        at ObservableObjectAdministration.Object.<anonymous>.ObservableObjectAdministration.read (/home/cdiesh/src/jbrowse-components/node_modules/mobx/lib/mobx.js:3853:37)
        at Object.get [as refName] (/home/cdiesh/src/jbrowse-components/node_modules/mobx/lib/mobx.js:4094:36)
        at RpcManager.refName (/home/cdiesh/src/jbrowse-components/packages/core/rpc/RpcManager.js:76:41)
        at tryCatch (/home/cdiesh/src/jbrowse-components/node_modules/regenerator-runtime/runtime.js:45:40)
        at Generator.invoke [as _invoke] (/home/cdiesh/src/jbrowse-components/node_modules/regenerator-runtime/runtime.js:271:22)
        at Generator.prototype.(anonymous function) [as next] (/home/cdiesh/src/jbrowse-components/node_modules/regenerator-runtime/runtime.js:97:21)
        at asyncGeneratorStep (/home/cdiesh/src/jbrowse-components/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
        at _next (/home/cdiesh/src/jbrowse-components/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        4.303s
Ran all test suites matching /packages\/jbrowse-web\/src\/JBrowse.test.js/i.
Done in 5.02s.
```

**Comment by cmdcolin** [comment]
This was fixed already (possibly 17b4add6ae0972)
