### ISSUE TITLE
@jbrowse/img not working with "window"

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#4205]
```
[
  ReferenceError: window is not defined
      at getActiveElementDeep (/home/cdiesh/.fnm/node-versions/v20.10.0/installation/lib/node_modules/@jbrowse/img/node_modules/react-dom/cjs/react-dom.development.js:7766:13)
      at getSelectionInformation (/home/cdiesh/.fnm/node-versions/v20.10.0/installation/lib/node_modules/@jbrowse/img/node_modules/react-dom/cjs/react-dom.development.js:7800:21)
      at prepareForCommit (/home/cdiesh/.fnm/node-versions/v20.10.0/installation/lib/node_modules/@jbrowse/img/node_modules/react-dom/cjs/react-dom.development.js:10163:26)
      at commitRootImpl (/home/cdiesh/.fnm/node-versions/v20.10.0/installation/lib/node_modules/@jbrowse/img/node_modules/react-dom/cjs/react-dom.development.js:23085:29)
      at unstable_runWithPriority (/home/cdiesh/.fnm/node-versions/v20.10.0/installation/lib/node_modules/@jbrowse/img/node_modules/scheduler/cjs/scheduler.development.js:468:12)
      at runWithPriority$1 (/home/cdiesh/.fnm/node-versions/v20.10.0/installation/lib/node_modules/@jbrowse/img/node_modules/react-dom/cjs/react-dom.development.js:11276:10)
      at commitRoot (/home/cdiesh/.fnm/node-versions/v20.10.0/installation/lib/node_modules/@jbrowse/img/node_modules/react-dom/cjs/react-dom.development.js:22990:3)
      at performSyncWorkOnRoot (/home/cdiesh/.fnm/node-versions/v20.10.0/installation/lib/node_modules/@jbrowse/img/node_modules/react-dom/cjs/react-dom.development.js:22329:3)
      at scheduleUpdateOnFiber (/home/cdiesh/.fnm/node-versions/v20.10.0/installation/lib/node_modules/@jbrowse/img/node_modules/react-dom/cjs/react-dom.development.js:21881:7)
      at updateContainer (/home/cdiesh/.fnm/node-versions/v20.10.0/installation/lib/node_modules/@jbrowse/img/node_modules/react-dom/cjs/react-dom.development.js:25482:3)
]

```

from office hours, regarding auto-generating a bunch of screenshots

**Comment by cmdcolin** [comment]
not sure what last working version was

**Comment by cmdcolin** [comment]
there is a sort of interesting reason for error....

the jbrowse-img tests try to force jest to run in the node environment instead of jsdom (browser-like) environment since it is a command line node tool, but this was not working because the code looked like this

```
/* eslint-disable tsdoc/syntax */ 
/**
 * @jest-environment node
 */
```

it was not using the node environment in this case

deleting the eslint-disable makes it work

**Comment by cmdcolin** [comment]
might be related to our existing eslint carve out here

```
{
      files: [
        '**/jbrowse-cli/**/*.test.ts',
        '**/jbrowse-cli/**/*.test.tsx',
        '**/jbrowse-img/**/*.test.ts',
      ],
      rules: {
        'tsdoc/syntax': 'off',
      },
    },

```
