### ISSUE TITLE
JBrowse issue

### ISSUE THREAD

**Issue by joccyyy** [GMOD/jbrowse-components#4332]
I got this error from JBrowse, here is the stack trace:

```

TypeError: Failed to fetch
TypeError: Failed to fetch
    at _callee$ (https://unpkg.com/@jbrowse/react-linear-genome-view/dist/react-linear-genome-view.umd.development.js:141968:18)
    at tryCatch (https://unpkg.com/@jbrowse/react-linear-genome-view/dist/react-linear-genome-view.umd.development.js:141845:1062)
    at Generator.<anonymous> (https://unpkg.com/@jbrowse/react-linear-genome-view/dist/react-linear-genome-view.umd.development.js:141845:3012)
    at Generator.next (https://unpkg.com/@jbrowse/react-linear-genome-view/dist/react-linear-genome-view.umd.development.js:141845:1699)
    at asyncGeneratorStep (https://unpkg.com/@jbrowse/react-linear-genome-view/dist/react-linear-genome-view.umd.development.js:141847:103)
    at _next (https://unpkg.com/@jbrowse/react-linear-genome-view/dist/react-linear-genome-view.umd.development.js:141848:194)
    at https://unpkg.com/@jbrowse/react-linear-genome-view/dist/react-linear-genome-view.umd.development.js:141848:364
    at new Promise (<anonymous>)
    at RemoteFileWithRangeCache.<anonymous> (https://unpkg.com/@jbrowse/react-linear-genome-view/dist/react-linear-genome-view.umd.development.js:141848:97)
    at RemoteFileWithRangeCache.checkAuthNeededFetch [as fetchImplementation] (https://unpkg.com/@jbrowse/react-linear-genome-view/dist/react-linear-genome-view.umd.development.js:141958:32)

```

**Comment by cmdcolin** [comment]
these errors "TypeError: Failed to fetch" are often generated from "cross origin" requests so is subject to CORS, or cross origin resource sharing. potentially we could improve the error message somewhat but you will need to make sure the server you are requesting from supports cors. This is guide from jbrowse 1 but should apply to jbrowse 2 https://jbrowse.org/docs/cors.html

**Comment by cmdcolin** [comment]
might close for now. if you have any more details let me know and i can advise
