### ISSUE TITLE
CI component_tests/lgv failed with possibly rare error

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#4347]
Error message:

```



  0 passing (861ms)
  1 failing

  1) JBrowse embedded view
       track loads:
     TypeError: The following error originated from your application code, not from Cypress.

  > Cannot read properties of undefined (reading 'showTrack')

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

https://on.cypress.io/uncaught-exception-from-application
      at <unknown> (http://localhost:5000/static/js/main.95495aa0.js:2:2451106)
      at Fl (http://localhost:5000/static/js/main.95495aa0.js:2:1960093)
      at t.unstable_runWithPriority (http://localhost:5000/static/js/main.95495aa0.js:2:2163244)
      at qo (http://localhost:5000/static/js/main.95495aa0.js:2:1900363)
      at Nl (http://localhost:5000/static/js/main.95495aa0.js:2:1959554)
      at <unknown> (http://localhost:5000/static/js/main.95495aa0.js:2:1959465)
      at L (http://localhost:5000/static/js/main.95495aa0.js:2:2162303)
      at w.port1.onmessage (http://localhost:5000/static/js/main.95495aa0.js:2:2161025)


```

link to log (temporary, is removed after 90 days or something) https://github.com/GMOD/jbrowse-components/actions/runs/8712609712/job/23899268332

the code used is

```
const state = createViewState({
      assembly,
      tracks,
      location: 'ctgA:1-100',
    })
    state.session.view.showTrack('volvox_cram')
```

I am surprised that this seems to show state.session.view being apparently undefined. if this is possible, then we may want to review our docs about how we recommend to use functions like showTrack

**Comment by cmdcolin** [comment]
I ran the test:e2e locally and it worked. it may be a hard-to-reproduce error

**Comment by cmdcolin** [comment]
might close this on for now. it is just too weird. if it does happen again, re-open
