### ISSUE TITLE
Minified stack trace source map resolution doesn't work on desktop

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#4404]
Example:
Follow steps from https://github.com/GMOD/jbrowse-components/issues/4403, get the 512Mb error, and click the "Show source map" and it will not work

will show something like

```
Error: Data exceeds maximum string length (512MB)

    at l.loadDataP (file:///Applications/JBrowse%202.app/Contents/Resources/app.asar/build/static/js/7809.b1b86892.chunk.js:1:493)
    at async l.getRefNames (file:///Applications/JBrowse%202.app/Contents/Resources/app.asar/build/static/js/7809.b1b86892.chunk.js:1:1263)
```

similar for linux appimage, not sure about windows

it would be a 'nice to have' to improve these stack traces, but it would require some method to figure out how to read the on-disk .map files (the "show stack trace" currently assumes a fetch against remote server for those resources. sometimes "fetch against the filesystem" works in electron in some cases, and not sure exactly the case but maybe not embedded in the app resources or not with certain permissions set)

**Comment by cmdcolin** [comment]
following same steps on web the error gives you the actual file name and line number

```
Error: Data exceeds maximum string length (512MB)
../../../plugins/gff3/src/Gff3Adapter/Gff3Adapter.ts:30:13

JBrowse 2.11.1

```
