### ISSUE TITLE
Desktop error reported

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-components#4454]
from email thread

 

```

Error: Error invoking remote method 'createInitialAutosaveFile': Error: Failed to load recent sessions file C:\Users\n18k1\AppData\Roaming\@jbrowse\desktop\recent_sessions.json: JSONParseError: Unexpected end of JSON input while parsing empty string

 

    at IpcRenderer.invoke (node:electron/js2c/renderer_init:2:6995)

    at async onClose (file:///C:/Users/n18k1/AppData/Local/Programs/@jbrowsedesktop/resources/app.asar/build/static/js/main.6f37a500.js:165:1840840)

    at async onClick (file:///C:/Users/n18k1/AppData/Local/Programs/@jbrowsedesktop/resources/app.asar/build/static/js/main.6f37a500.js:165:1624618)

```

**Comment by cmdcolin** [comment]
@carolinebridge that error should have been fixed in v2.12.3

https://jbrowse.org/jb2/blog/2024/06/27/v2.12.3-release/ (PR https://github.com/GMOD/jbrowse-components/pull/4469)

i think the one for this thread is a bit separate
