### ISSUE TITLE
Error loading source map, showing raw stack trace below: Error: Failed to fetch fetching https://s3.amazonaws.com/agrjbrowse/MOD-jbrowses/WormBase/static_tracks/modencode-bucket/fasta/current/c_elegans.PRJNA13758.WS278.genomic.fa.gz.fai      at RemoteFileWithRangeCache.fetch (https://unpkg.com/@jbrowse/react-linear-genome-view/dist/react-linear-genome-view.umd.development.js:228571:27)     at async RemoteFileWithRangeCache.readFile (https://unpkg.com/@jbrowse/react-linear-genome-view/dist/react-linear-genome-view.umd.development.js:228634:21)     at async readFAI (https://unpkg.com/@jbrowse/react-linear-genome-view/dist/react-linear-genome-view.umd.development.js:28556:18)     at async BgzipIndexedFasta.getSequenceSizes (https://unpkg.com/@jbrowse/react-linear-genome-view/dist/react-linear-genome-view.umd.development.js:28636:21)

### ISSUE THREAD

**Issue by zsz1118** [GMOD/jbrowse-components#4479]
I got this error from JBrowse, here is the stack trace:

```
Error loading source map, showing raw stack trace below:
Error: Failed to fetch fetching https://s3.amazonaws.com/agrjbrowse/MOD-jbrowses/WormBase/static_tracks/modencode-bucket/fasta/current/c_elegans.PRJNA13758.WS278.genomic.fa.gz.fai

    at RemoteFileWithRangeCache.fetch (https://unpkg.com/@jbrowse/react-linear-genome-view/dist/react-linear-genome-view.umd.development.js:228571:27)
    at async RemoteFileWithRangeCache.readFile (https://unpkg.com/@jbrowse/react-linear-genome-view/dist/react-linear-genome-view.umd.development.js:228634:21)
    at async readFAI (https://unpkg.com/@jbrowse/react-linear-genome-view/dist/react-linear-genome-view.umd.development.js:28556:18)
    at async BgzipIndexedFasta.getSequenceSizes (https://unpkg.com/@jbrowse/react-linear-genome-view/dist/react-linear-genome-view.umd.development.js:28636:21)
```

**Comment by cmdcolin** [comment]
it looks like you are using the embedded code (from the "vanillajs" unpkg react-linear-genome-view link)  and the wormbase files. that seems like it should be fine. do you hve the code you are using for embedded? maybe this was just a trasient network error?
