### ISSUE TITLE
JBrowse issue viewing of gencode 44 GTF string length exceeds maximum

### ISSUE THREAD

**Issue by callumparr** [GMOD/jbrowse-components#4522]
I got this error from JBrowse, here is the stack trace:

```
Error: Data exceeds maximum string length (512MB)

    at j.loadDataP (file:///Applications/JBrowse%202.app/Contents/Resources/app.asar/build/static/js/4587.8ef1ada2.chunk.js:1:8711)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async j.getRefNames (file:///Applications/JBrowse%202.app/Contents/Resources/app.asar/build/static/js/4587.8ef1ada2.chunk.js:1:9199)
```

I am trying to load and view the standard comprehensive transcript annotation GTF (Version 44) from Gencode.

Please advise or recommend that would be much appreciated.

**Comment by cmdcolin** [comment]
If you use the GFF3 from gencode, you should be able to load the file. The GTF parser doesn't have the workaround for this limitation yet but we could work on that

**Comment by callumparr** [comment]
> If you use the GFF3 from gencode, you should be able to load the file. The GTF parser doesn't have the workaround for this limitation yet but we could work on that

Thank you. I am currently doing this, but I cannot get the transcript ID to show next to the feature like I can with GTF. It is bit tricky to know which is which when there are many under a gene and looking through the details panel. Is there some setting I can change for this? I can see them when I bring in my own GTF. 
![jbrowse](https://github.com/user-attachments/assets/e0a6d7d3-090d-4e7d-8ff5-51706f2eaf44)

**Comment by cmdcolin** [comment]
indeed, there is an ongoing issue where we need to find a way to show transcript names for the individual transcripts in a gene glyph. that issue is located here https://github.com/GMOD/jbrowse-components/issues/241

**Comment by cmdcolin** [comment]
(so, you are not missing any hidden setting, it's just still a needed todo for us)

**Comment by cmdcolin** [comment]
if you are using the web version, you can use the latest "nightly" build

`jbrowse upgrade --nightly`

if you are using desktop, the fix will be in the next release.

pr for fix https://github.com/GMOD/jbrowse-components/pull/4523

thanks for the bug report, it helps to know what issues people run into :)

**Comment by cmdcolin** [comment]
(^^the fix is to allow large plaintext gtf)

**Comment by cmdcolin** [comment]
proper fix is now released in v2.15.0 :)
