### ISSUE TITLE
gz headers with rclone serve

### ISSUE THREAD

**Issue by alpapan** [GMOD/jbrowse-components#4621]
`  @jbrowse/cli/2.15.4 linux-x64 node-v18.12.1`

i'm a bit lost with supporting bgzip fasta

```
Error: problem decompressing block: incorrect gzip header check

../../../node_modules/@gmod/bgzf-filehandle/src/unzip-pako.ts:51:13 (at s ()
../../../node_modules/@gmod/bgzf-filehandle/src/bgzFilehandle.ts:89:34 (at d._readAndUncompressBlock ()
../../../node_modules/@gmod/bgzf-filehandle/src/bgzFilehandle.ts:112:13 (at async d.read ()
../../../node_modules/@gmod/indexedfasta/src/indexedFasta.ts:218:5 (at async l._fetchFromIndexEntry ()
JBrowse 2.15.4
```

example config (from a cram) is

```
{
      "type": "AlignmentsTrack",
      "trackId": "track1",
      "name": "CRAM: Alignment",
      "adapter": {
        "type": "CramAdapter",
        "cramLocation": {
          "uri": "XYZ/bam/bob.cram"
          "locationType": "UriLocation"
        },
        "craiLocation": {
          "uri": "XYZ/bam/bob.cram.crai"
          "locationType": "UriLocation"
        },"sequenceAdapter": {
          "type": "BgzipFastaAdapter",
          "fastaLocation": {
            "uri": "XYZ/seq.fa.gz",
            "locationType": "UriLocation"
          },
          "faiLocation": {
            "uri": "XYZ/fa.gz.fai",
            "locationType": "UriLocation"
          },
          "gziLocation": {
            "uri": "XYZ/fa.gz.gzi",
            "locationType": "UriLocation"
          }
      }

      },
      "category": [
        "Alignments"
      ],
      "assemblyNames": [
        "XXX"
      ]
    }
    ```

(same problem with the reference sequence)

i'm using rclone serve http to provide the files, not an apache server... any ideas? i could just not use bgzip fasta and just serve it raw?

**Comment by cmdcolin** [comment]
this most likely is a thing where the server is adding "Content-Encoding: gzip" which really messes us up. i should probably do a whole write up on this issue at some point because it is multi-faceted and difficult. it has caused problems with all kinds of bgzip stuff such as bgzip indexed fasta, bam, and tabix stuff.

sometimes the server side logic is as 'simple' as to detect a file with .gz extension and then add the header, and since jbrowse does not want to header, you can rename the file to something that is not .gz e.g. .bgz or something else. sometimes the server side logic is a bit more complex and investigates the file contents and this is more tricky to bypass

**Comment by alpapan** [comment]
great idea. I can confirm renaming works

```
curl -I https://example.com/rclonedata/data.fa.gz

HTTP/2 200
accept-ranges: bytes
content-length: 72884265
content-type: application/gzip
last-modified: Fri, 08 Mar 2024 04:30:08 GMT
server: rclone/v1.65.2
date: Thu, 24 Oct 2024 08:43:10 GMT
content-language: fa
```

vs

```
curl -I https://example.com/rclonedata/data.fa.bgz

HTTP/2 200
accept-ranges: bytes
content-length: 72884265
content-type: application/octet-stream
last-modified: Fri, 08 Mar 2024 04:30:08 GMT
server: rclone/v1.65.2
date: Thu, 24 Oct 2024 15:34:03 GMT
content-language: fa
```

**Comment by alpapan** [comment]
i spoke too soon, while the curl returns an octet-stream, the (edge) browser still reports an error... no idea why....

**Comment by cmdcolin** [comment]
the Content-Type is not the same as Content-Encoding and to my knowledge the Content-Encoding is the main culprit in a lot of these bugs. if you can go into the "devtools" in the browser and look at the response headers from the server and see what it is returning, it might be of interest.

**Comment by alpapan** [comment]
ok, i don't get it.... can it be the content-language thinking fa is farsi?!

this config does not work:
```
{
  "type": "ReferenceSequenceTrack",
  "trackId": "example1-ReferenceSequenceTrack",
  "adapter": {
    "type": "BgzipFastaAdapter",
    "fastaLocation": {
      "locationType": "UriLocation",
      "uri": "https://example.com/rclonedata/example1.fa.bgz"
    },
    "faiLocation": {
      "locationType": "UriLocation",
      "uri": "https://example.com/rclonedata/example1.fa.bgz.fai"
    },
    "metadataLocation": {
      "locationType": "UriLocation",
      "uri": "/path/to/fa.metadata.yaml"
    },
    "gziLocation": {
      "locationType": "UriLocation",
      "uri": "https://example.com/rclonedata/example1.fa.bgz.gzi"
    }
  },
  "displays": [
    {
      "type": "LinearReferenceSequenceDisplay",
      "displayId": "example1-ReferenceSequenceTrack-LinearReferenceSequenceDisplay"
    },
    {
      "type": "LinearGCContentDisplay",
      "displayId": "example1-ReferenceSequenceTrack-LinearGCContentDisplay"
    }
  ]
}
# response header:
accept-ranges:
bytes
content-language:
fa
content-length:
63596
content-type:
application/octet-stream
date:
Thu, 24 Oct 2024 16:15:26 GMT
last-modified:
Wed, 23 Oct 2024 07:44:32 GMT
server:
rclone/v1.65.2



```

but this does
```
{
  "type": "ReferenceSequenceTrack",
  "trackId": "example2-ReferenceSequenceTrack",
  "adapter": {
    "type": "BgzipFastaAdapter",
    "fastaLocation": {
      "locationType": "UriLocation",
      "uri": "https://example.com/rclonedata/example.fasta.bgz"
    },
    "faiLocation": {
      "locationType": "UriLocation",
      "uri": "https://example.com/rclonedata/example.fasta.bgz.fai"
    },
    "metadataLocation": {
      "locationType": "UriLocation",
      "uri": "/path/to/fa.metadata.yaml"
    },
    "gziLocation": {
      "locationType": "UriLocation",
      "uri": "https://example.com/rclonedata/example.fasta.bgz.gzi"
    }
  },
  "displays": [
    {
      "type": "LinearReferenceSequenceDisplay",
      "displayId": "example2-ReferenceSequenceTrack-LinearReferenceSequenceDisplay"
    },
    {
      "type": "LinearGCContentDisplay",
      "displayId": "example2-ReferenceSequenceTrack-LinearGCContentDisplay"
    }
  ]
}
# response header:
accept-ranges:
bytes
content-length:
34588
content-type:
application/octet-stream
date:
Thu, 24 Oct 2024 16:15:26 GMT
last-modified:
Fri, 26 Jan 2024 00:46:17 GMT

server:
rclone/v1.65.2

```

**Comment by alpapan** [comment]
ok so the .fa was weird to be interpreted as a language but after renaming all the files i still can't fix it. 

this is the response header
```
#canu3_mdb2_hifiasm.a_ctg.fasta.bgz.fai
accept-ranges:
bytes
content-length:
63596
content-type:
application/octet-stream
date:
Thu, 24 Oct 2024 17:25:26 GMT
last-modified:
Wed, 23 Oct 2024 07:44:32 GMT

server:
rclone/v1.65.2


``` 

similar for the .bgz and .bgz.gzi files


console error
```
Error: problem decompressing block: incorrect gzip header check
    at i (unzip-pako.ts:51:13)
    at d._readAndUncompressBlock (bgzFilehandle.ts:89:34)
    at async d.read (bgzFilehandle.ts:112:13)
    at async l._fetchFromIndexEntry (indexedFasta.ts:218:5)
setError | @ | serverSideRenderedBlock.ts:151
...
```

**Comment by alpapan** [comment]
ok so i fix it.

- i rebuilt the bgzip but the file was the same
- i moved it to another directory which perhaps overrode the rclone cache and that did fix it

also
- i think the .fa naming might have been an issue because out of a few 100 tracks, it was the only one with .fa (instead of fasta) and had an issue
- i don't think the .gz naming was an issue because i had lots of other tracks with .gz and they didn't seem to be causing it (but now i'm naming them all .bgz JustInCase

i'm closing ticket but i will update if i discover anything new.
