### ISSUE TITLE
JBrowse issue

### ISSUE THREAD

**Issue by aprlopez** [GMOD/jbrowse-components#4700]
I got this error from JBrowse, here is the stack trace:

```
Error: Cannot create a string longer than 0x1fffffe8 characters

    at Object.slice (node:buffer:633:37)
    at Buffer.toString (node:buffer:861:14)
    at file:///Applications/JBrowse%202.app/Contents/Resources/app.asar/build/static/js/9870.7f68fa03.chunk.js:1:5023
    at async o.getSequenceSizes (file:///Applications/JBrowse%202.app/Contents/Resources/app.asar/build/static/js/9870.7f68fa03.chunk.js:1:5526)
    at async h.getRegions (file:///Applications/JBrowse%202.app/Contents/Resources/app.asar/build/static/js/9870.7f68fa03.chunk.js:1:564)
    at async Object.loadPre (file:///Applications/JBrowse%202.app/Contents/Resources/app.asar/build/static/js/main.ef79700d.js:197:1630112)
```

**Comment by cmdcolin** [comment]
can you describe the procedure that resulted in this error and what version of JBrowse you were using? I can make some guesses like maybe you opened the fasta as the fai  file from accidentally but i am not quite sure

**Comment by cmdcolin** [comment]
i am going to convert this to a discussion thread but let me know if you have any more details. I would suggest checking that you loaded a fasta index (.fai) properly...we may be able to add a runtime check to help with this
