### ISSUE TITLE
"Cannot read properties of null" when viewing feature sequence

### ISSUE THREAD

**Issue by Sarsaparella** [GMOD/jbrowse-components#4726]
Hello! When I open my custom bed track, choose feature and click on "show feature sequence" it gives me "TypeError: Cannot read properties of null (reading 'sort')". Before the last update everything worked fine with the same bed track. 
![image](https://github.com/user-attachments/assets/bdf7ed2c-eb2a-4e83-881d-a05f0c26a869)
Here is the stack trace:
```
TypeError: Cannot read properties of null (reading 'sort')
TypeError: Cannot read properties of null (reading 'sort')
    at C (file:///tmp/.mount_jbrowsjysvf2/resources/app.asar/build/static/js/6999.3cb16f1b.chunk.js:1:5043)
    at gi (file:///tmp/.mount_jbrowsjysvf2/resources/app.asar/build/static/js/main.acc0202d.js:197:953170)
    at Al (file:///tmp/.mount_jbrowsjysvf2/resources/app.asar/build/static/js/main.acc0202d.js:197:1012111)
    at yc (file:///tmp/.mount_jbrowsjysvf2/resources/app.asar/build/static/js/main.acc0202d.js:197:1001363)
    at bc (file:///tmp/.mount_jbrowsjysvf2/resources/app.asar/build/static/js/main.acc0202d.js:197:1001291)
    at gc (file:///tmp/.mount_jbrowsjysvf2/resources/app.asar/build/static/js/main.acc0202d.js:197:1001154)
    at oc (file:///tmp/.mount_jbrowsjysvf2/resources/app.asar/build/static/js/main.acc0202d.js:197:997989)
    at ac (file:///tmp/.mount_jbrowsjysvf2/resources/app.asar/build/static/js/main.acc0202d.js:197:996545)
    at x (file:///tmp/.mount_jbrowsjysvf2/resources/app.asar/build/static/js/main.acc0202d.js:197:1184716)
    at Immediate._ (file:///tmp/.mount_jbrowsjysvf2/resources/app.asar/build/static/js/main.acc0202d.js:197:1185248)
```
And here is a part of my bed file (hg38 genome):
```
chr	start	end	annot	score	strand
1	206773515	206773537	feature1	-	+
1	206773669	206773688	feature2	-	-
```

Thank you! <3

**Comment by cmdcolin** [comment]
thanks for reporting this, I found this was indeed a bug and found a fix for it here https://github.com/GMOD/jbrowse-components/pull/4727
